In [3]:
# Import the relevant libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression


In [4]:
# Load the data

data = pd.read_csv('real_estate_price_size_year.csv')

In [5]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [6]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [7]:
# Create the regression

# Declare the dependent and independent variable

x = data[['size', 'year']]
y = data['price']

In [1]:
# Standardization
# Full documentation: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [2]:
# Import the preprocessing module
# StandardScaler is one of the easiest and 'cleanest' ways to preprocess your data
from sklearn.preprocessing import StandardScaler

In [8]:
# Create a StandardScaler instance
scaler = StandardScaler()

In [9]:
# Fit the input data (x)
# Essentially we are calculating the mean and standard deviation feature-wise 
# (the mean of 'size' and the standard deviation of 'size', 
# as well as the mean of 'year' and the standard deviation of 'year')
scaler.fit(x)

StandardScaler()

In [10]:
# The actual scaling of the data is done through the method 'transform()'
# Let's store it in a new variable, named appropriately
x_scaled = scaler.transform(x)

In [11]:
# Whenever we get new data we can use the same scaler defined above to standardize it e.g.

# new_data = pd.read_csv('new_data.csv)
# new_data_scaled = scaler.transform(new_data)

In [12]:
# The result is an ndarray
x_scaled

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [13]:
# Regression

reg = LinearRegression() #reg is an instance of the linear regression class
reg.fit(x_scaled,y) #fit the regression

LinearRegression()

In [14]:
# Find the intercept

reg.intercept_

292289.4701599997

In [15]:
# Find the coefficients

reg.coef_

array([67501.57614152, 13724.39708231])

In [16]:
# Calculate the R-squared (measure of goodness of it of your model)
# R-squared is the variability explained by the regression divided by total variability of the dataset. In field such as chemistry and physics R2 ~ 0.7 - 0.99. In social sciences e.g. economics R2 ~ 0. could be ok depending on number of variables. 
# Total variabilty = Variability explained by regression (SSR) + Unexplained variability (SSE)

reg.score(x_scaled,y)

0.7764803683276793

In [17]:
# size and year explain 77.6% of the variabilty of price of apartments in our sample

In [18]:
# Calculate the Adjusted R-squared (Penalizes the excessive use of variables)
# Adjusted R-sqaured 
#R2adj. = 1 - (1-R2) * n-1/n-p-1
# Change to markdown and write the formuale in latex code for a nice display in Jupyter 

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [19]:
x.shape

(100, 2)

In [20]:
r2 = reg.score(x_scaled,y)
n = x_scaled.shape[0]
p = x_scaled.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.77187171612825

In [37]:
# Compare the R-squared and the Adjusted R-squared

# It seems the the R-squared is only slightly larger than the Adjusted R-squared, implying that we were not penalized a lot for the inclusion of 2 independent variables.


In [21]:
# Compare the R-squared of this regression and the simple linear regression where only 'size' was used

In [23]:
# Making predictions with the standardized coefficients (weights)
# Find the price of an apartment that has a size of 750 sq.ft. from 2009

# For simplicity, let's create a new dataframe with 2 *new* observations
new_data = pd.DataFrame(data=[[750,2009]], columns=['size','year'])
new_data

size  year
0   750  2009

In [24]:
# We can make a prediction for a whole dataframe (not a single value)
reg.predict(new_data)

/Users/anthonyoyoo/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([78490785.31465863])

In [25]:
# Our model is expecting SCALED features (features of different magnitude)
# In fact we must transform the 'new data' in the same way as we transformed the inputs we train the model on
# Luckily for us, this information is contained in the 'scaler' object
# We simply transform the 'new data' using the relevant method
new_data_scaled = scaler.transform(new_data)

# Let's check the result
new_data_scaled

array([[-0.34752816, -0.76509206]])

In [26]:
# Finally we make a prediction using the scaled new data
reg.predict(new_data_scaled)
# The output is much more appropriate, isn't it?

array([258330.34465995])

In [ ]:
# the price of a 750 sq.ft. from 2009 apartment is predicted to be $ 258,330

In [40]:
#Calculate the univariate p-values of the variables (For feature selection)

#Reminder: a p-value < 0.05 means that the variable is significant. Therefore the coefficient is most probably differemt from zero.
#The idea here is to identify the explanatory power of the variables (features) we have included in the model.

In [27]:
# Import the releant libraries

from sklearn.feature_selection import f_regression


In [28]:
# Calculate the F-regression

f_regression(x_scaled,y)


(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [29]:
# Getting just the p-values
p_values = f_regression(x_scaled,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [30]:
# Format in non-scientific notation
p_values.round(3)

array([0.   , 0.357])

In [46]:
# Interprete the p-values

# p-value of size = 0. This means size is a significant predictor of apartment price. 
# p-value of year = 0.357. This p-value is > 0.05, therefore year is not a significant predictor of apartment price. We can omit it from the model without losing mcuh predictive power.

In [43]:
# Creating a summary table

reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)


In [44]:
reg_summary

Features  Coefficients  p-values
0     size  67501.576142     0.000
1     year  13724.397082     0.357

In [34]:
# Note that: 
# year does not contribute to our model and should be removed.
# p-values are one of the best ways to determine if a variable is redundant,
# but they provide no information whatsoever about HOW USEFUL a variable a variable is.
# i.e. two variables can both have a p-value of 0.000 making them relevant, but this does not mean they are equally important.


In [35]:
# Multivariate p-value calculation

# As suggested in the previous lecture, the F-regression does not take into account the interrelation of the features. A not so simple fix for that is to ammend the LinearRegression() class. You can find the relevant code with comments below. 

In [36]:
# How to properly include p-values in sklearn

# Since the p-values are obtained through certain statistics, we need the 'stat' module from scipy.stats
import scipy.stats as stat  

# and of course the actual regression (machine learning) module
from sklearn import linear_model

In [37]:
# Since we are using an object oriented language such as Python, we can simply define our own 
# LinearRegression class (the same one from sklearn)
# By typing the code below we will ovewrite a part of the class with one that includes p-values
# Here's the full source code of the ORIGINAL class: https://github.com/scikit-learn/scikit-learn/blob/7b136e9/sklearn/linear_model/base.py#L362

class LinearRegression(linear_model.LinearRegression):
    
    # LinearRegression class after sklearn's, but calculate t-statistics
    # and p-values for model coefficients (betas).
    # Additional attributes available after .fit()
    # are `t` and `p` which are of the shape (y.shape[1], X.shape[1])
    # which is (n_features, n_coefs)
    # This class sets the intercept to 0 by default, since usually we include it
    # in X.

    # nothing changes in __init__
    def __init__(self, fit_intercept=True, normalize=False, copy_X=True,
                 n_jobs=1, positive = False):
        self.fit_intercept = fit_intercept
        self.normalize = normalize
        self.copy_X = copy_X
        self.n_jobs = n_jobs
        self.positive = positive

    def fit(self, X, y, n_jobs=1):
        self = super(LinearRegression, self).fit(X, y, n_jobs)

        # Calculate SSE (sum of squared errors)
        # and SE (standard error)
        sse = np.sum((self.predict(X) - y) ** 2, axis=0) / float(X.shape[0] - X.shape[1])
        se = np.array([np.sqrt(np.diagonal(sse * np.linalg.inv(np.dot(X.T, X))))])

        # compute the t-statistic for each feature
        self.t = self.coef_ / se
        # find the p-value for each feature
        self.p = np.squeeze(2 * (1 - stat.t.cdf(np.abs(self.t), y.shape[0] - X.shape[1])))
        return self

In [38]:
# When we create the regression everything is the same
reg_with_pvalues = LinearRegression()
reg_with_pvalues.fit(x,y)

LinearRegression()

In [39]:
# The difference is that we can check what's contained in the local variable 'p' in an instance of the LinearRegression() class
reg_with_pvalues.p

array([0., 0.])

In [40]:
# Let's create a new data frame with the names of the features
reg_summary = pd.DataFrame(data=x.columns.values, columns =['Features'])
# Then we create and fill a second column, called 'Coefficients' with the coefficients of the regression
reg_summary['Coefficients'] = reg_with_pvalues.coef_
# Finally, we add the p-values we just calculated
reg_summary['p-values'] = reg_with_pvalues.p.round(3)

In [41]:
reg_summary

Features  Coefficients  p-values
0     size    227.700854       0.0
1     year   2916.785327       0.0

In [42]:
# check why p-value for year is 0.0